server:
  port: 8088
spring:
  application:
    name: xc-freemarker-test #指定服务名
  freemarker:
    cache: false  #关闭模板缓存,方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间, 设置为0表示立即检查，如果时间大于0会有缓存不方便
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: xc_cms